# arb-dir: lib/common/localization/arb
# template-arb-file: app_en.arb
# # output-dir: lib/generated
# output-localization-file: app_localizations.dart
# 

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false