name: rick_and_morty
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.0
  flutter_svg: ^2.0.6
  # meta: ^1.10.0
  bloc: ^8.1.2
  logger: ^2.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  bloc_concurrency: ^0.2.4
  rxdart: ^0.27.7
  meta: ^1.11.0
  mockito: ^5.4.4
  graphql_flutter: ^5.2.0-beta.8
  graphql: ^5.2.0-beta.11

dev_dependencies:
  flutter_lints: ^3.0.0
  mocktail: 1.0.3
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/common/gen/
  integrations:
    flutter_svg: true

flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 600

